### ISSUE TITLE
Licenza

### ISSUE THREAD

**Issue by Stypox** [SergioFacchini/Trentastico#1]
Ciao, grazie per aver reso Trentastico open source e grazie per il tuo lavoro!

Penso che dovresti mettere una licenza, per effettivamente specificare come il codice può essere riusato. Ti consiglio GPLv3 se vuoi che diventi "software libero", che garantirebbe anche che nessuno possa _legalmente_ prendere la tua app, aggiungere pubblicità closed source e pubblicare un clone su play store. Altrimenti c'è MIT che è meno restrittiva. Comunque puoi dare un'occhiata [qui](https://github.com/readme/guides/open-source-licensing).

Una volta che c'è una licenza magari mi metto a pubblicarla su F-Droid, una repository di applicazioni libere, se a te va bene. https://f-droid.org/

**Comment by SergioFacchini** [comment]
Ciao @Stypox, grazie mille per l'idea! Ho aggiunto la licenza GPLv3 come mi avevi suggerito. Purtroppo non sono un grande esperto di licenze e non so se devo fare altro oltre che aggiungere il file LICENCE.md.

Va benissimo se vuoi pubblicare su https://f-droid.org!

**Comment by Stypox** [comment]
Grazie!
